// <auto-generated />
using System;
using FinancialControl.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialControl.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231020145445_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinancialControl.Core.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Value")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Date = new DateTime(2023, 10, 20, 11, 54, 45, 459, DateTimeKind.Local).AddTicks(2156),
                            Description = "Mensalidade facul",
                            Value = 700m
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Date = new DateTime(2023, 10, 20, 11, 54, 45, 459, DateTimeKind.Local).AddTicks(2614),
                            Description = "Internet",
                            Value = 70m
                        });
                });

            modelBuilder.Entity("FinancialControl.Core.Models.Revenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Value")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)");

                    b.HasKey("Id");

                    b.ToTable("Revenues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 10, 20, 11, 54, 45, 459, DateTimeKind.Local).AddTicks(2058),
                            Description = "Salário",
                            Value = 3000m
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 10, 20, 11, 54, 45, 459, DateTimeKind.Local).AddTicks(2128),
                            Description = "Salário bônus",
                            Value = 3000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
